### ISSUE TITLE
Link Question

### ISSUE THREAD

**Issue by PeteHollyer** [pbek/QOwnNotes#1977]
Is there a way to link to another note, specifying the Header(#) in that not to jump too?
this links to another Note:

 [Main Menu](MainMenu.md)

But I want to not only link to MainMenu.md but to Header "#Chapter5" 

Some of the Markdown editors I've payed with allow/support this others don't

**Comment by pbek** [comment]
No, sorry. That would be nice, but hard to implement consistently and without regressions. 😅

**Comment by pbek** [comment]
So we are talking about links like: `[Heading Test](Heading%20Test.md#my-heading)`

There would be lots of things to do (possibly even more)...

## Todo

- [ ] find algorithm to transform headings into an anchor text (there are many restrictions on anchors)
- [ ] find algorithm to transform anchor texts back into headings
- [ ] note link syntax highlighting in note text edit (and invalid link highlighting)
- [ ] note link clicking note text edit
- [ ] note link clicking note preview
- [ ] jumping to heading in note text edit
- [ ] jumping to heading in preview (headings need anchor links)
- [ ] note link migration over all notes when heading is changed
- [ ] all of the above for heading links in the current note `[My Heading](#my-heading)` 😅

**Comment by pbek** [comment]
## 21.10.7
- you can now add an url-encoded heading to a note link as url fragment to
  attempt to jump to that heading in the linked note when clicking the link
  (for [#1977](https://github.com/pbek/QOwnNotes/issues/1977))
    - this works with opening links in the note text edit and the preview 
    - `[my note](my-note.md#First%20heading)` will attempt to jump to a heading
      `First heading` in note `my-note.md` (note that `%20` is decoded as space)
    - the heading will be searched with the in-note search, so for the link
      `[my note](my-note.md#First%20heading)` there will be searched for the
      text `## First heading` inside the note
    - this feature is still *work in progress*

**Comment by pbek** [comment]
## 21.10.8
- more features were added to the **heading links** feature (for [#1977](https://github.com/pbek/QOwnNotes/issues/1977))
    - the search panel inside the note is now closed after jumping to the heading
    - the broken note link checker now also works with links with an url fragment
    - you can now select a heading to link to in the note link dialog

**Comment by pbek** [comment]
Phew... This one hurt... I hope nothing breaks. But this should conclude this feature request.

## 21.10.9
- there now will be a warning that a restart of the application is needed when
  changing the default note file extension (for [#2250](https://github.com/pbek/QOwnNotes/pull/2250)) 
- more features were added to the **linking of note heading** (for [#1977](https://github.com/pbek/QOwnNotes/issues/1977))
    - if a note and a heading were selected in the note link dialog the heading
      text will be added to the link title by default
    - if the current note is selected in the note link dialog the correct note
      file name will be used now instead of `.` to allow links to headings in
      the current note
    - when a note is renamed or moved to another sub-folder note links with
      heading fragments can now also be automatically renamed
        - this also works with note links to the current note
        - warning: this feature (especially the part with links to the current note)
          was very complex and might introduce regressions

There now is a new release, could you please test it and report if it works for you?

**Comment by tragtragtrag** [comment]
I see, thank you much for this explanation! So, now my next question would be: Is there a script or something similar that changes all the headings of all my .md-notes one level down? :) (just joking, no need to answer, don't expect this to exist)

**Comment by pbek** [comment]
So how do you notes look like?


```
My note title
========

## my headline

some text
```
