### ISSUE TITLE
Switch to GitHub releases as hosting service for source archive

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2799]
Since the [TuxFamily](https://www.tuxfamily.org/) upload server has been very unreliable and down for several days, we will switch to GitHub releases as hosting service for the source archive.

### Todo

- [x] write upload script
- [x] update release GitHub action `.github/workflows/build-release.yml` to immediately release
    - [x] determine if api.qownnotes.org is ok with that
- [x] use `build-systems/github/build-github-src.sh` in `build-systems/build-all.sh`
    - [x] add `gh` to `build-systems/Dockerfile`
    - [x] how do we handle login? otherwise, a token will be generated every time!
        - [x] find file where token is stored and make that mountable to cryfs share? **Prio1**
- [x] replace `download.tuxfamily.org/qownnotes` in QOwnNotes git repository
    - [x] search/replace for `tuxfamily`
    - [x] upload translation sources
- [x] replace in <https://github.com/qownnotes/gentoo-overlay>
    - was clean
- [x] replace in <https://aur.archlinux.org/packages/qownnotes/>
    - shouldn't have anything
- [x] open issue on <https://github.com/flathub/org.qownnotes.QOwnNotes>
    - <https://github.com/flathub/org.qownnotes.QOwnNotes/issues/182>
- [x] replace in nixcfg
- [x] do a release 23.7.1
    - [x] mention in changelog
    - [x] build `build-systems/Dockerfile` for `gh`
    - [x] test build script
    - [x] check if release is published immediately
- [x] replace in nixpkgs and create PR for new release
    - <https://github.com/NixOS/nixpkgs/pull/243123>
- [x] write blog post to be posted to social media
    - [x] link to issue

**Comment by pbek** [comment]
@TimB87, did this work for you?

**Comment by TimB87** [comment]
@pbek Works perfectly fine, thank you very much :)
